name: Build & Test WPF App (.NET Framework)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet packages
        run: nuget restore Pipeline.sln

      - name: Build solution
        run: msbuild Pipeline.sln /p:Configuration=Release

      - name: Run analyzers and treat warnings as errors
        run: msbuild Pipeline.sln /p:RunAnalyzers=true /p:TreatWarningsAsErrors=true

      - name: Run MSTest unit tests
        shell: pwsh
        run: |
            Get-Command vstest.console.exe | Select-Object -ExpandProperty Source

      - name: Upload WPF build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wpf-build
          path: Pipeline\bin\Release\
